version: "3"

services:
  webserver:
    ports:
      - "8080:80"
    environment:
      DB_USER: root
      DB_PASS: toor
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "baratito"
      GOOGLE_CLIENT_IDS: "42161830547-tib7uiqu7k0ss8veja6jm6npb4tlnf6g.apps.googleusercontent.com,42161830547-2tmeb3hsacdf5ri1eujvc9a2s105m629.apps.googleusercontent.com"
    depends_on:
      - db
    networks: 
      - db
      

  db:
    image: "postgres:13"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "toor"
      PGDATA: "/data/postgres"
    volumes:
      - ./postgress_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

    networks: 
      - db
  
  pgadmin:
    image: "dpage/pgadmin4:4.30"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - ./pgadmin_server.json:/pgadmin4/servers.json
    ports:
      - "5433:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'db:5432:*:root:toor' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped
    networks: 
      - db

  redis_handler:
    image: redis_handler
    environment:
      REDIS_HOST: "redis"
      REDIS_PASSWORD: "420piedrabuena"
      REDIS_PORT: "6379"
      DB_USER: root
      DB_PASS: toor
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "baratito"
    restart: always
    depends_on:
      - redis
    networks: 
      - db

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 420piedrabuena
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: always
    networks: 
      - db
networks:
  db:
