version: "3"

services:
  webserver:
    build: .
    restart: always
    volumes:
      - ./app:/app
      - ./alembic:/alembic
      - ./alembic.ini:/alembic.ini
      - ./static:/static
    environment:
      DB_USER: root
      DB_PASS: toor
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "baratito"

    labels:
      - traefik.enable=true
      - traefik.http.services.app.loadbalancer.server.port=80
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`api.baratito.app`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`api.baratito.app`)
      - traefik.http.routers.app-https.tls=true
      - traefik.http.routers.app-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
