"""Add cascade

Revision ID: 104837aaa066
Revises: e98e27a4aaf4
Create Date: 2021-11-24 19:23:33.130228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "104837aaa066"
down_revision = "e98e27a4aaf4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "purchase_list_item_purchase_list_id_fkey", "purchase_list_item", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "purchase_list_item",
        "purchase_list",
        ["purchase_list_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "purchase_list_item", type_="foreignkey")
    op.create_foreign_key(
        "purchase_list_item_purchase_list_id_fkey",
        "purchase_list_item",
        "purchase_list",
        ["purchase_list_id"],
        ["id"],
    )
    # ### end Alembic commands ###
