"""Added fields

Revision ID: 13193df545e3
Revises: a4392f55d358
Create Date: 2021-11-29 22:59:06.400162

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "13193df545e3"
down_revision = "a4392f55d358"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchase_list", sa.Column("start_longitude", sa.Float(), nullable=True))
    op.add_column("purchase_list", sa.Column("start_latitude", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_list", "start_latitude")
    op.drop_column("purchase_list", "start_longitude")
    # ### end Alembic commands ###
