"""Added purchase estimated_price column

Revision ID: 195f6cbef364
Revises: ac2e8624658c
Create Date: 2021-11-12 05:42:05.505574

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "195f6cbef364"
down_revision = "ac2e8624658c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("purchase_list", sa.Column("estimated_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_list", "estimated_price")
    # ### end Alembic commands ###
