"""Added product price table

Revision ID: 30dc864bba2d
Revises: cbe2acc6e667
Create Date: 2021-10-17 03:45:37.896253

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "30dc864bba2d"
down_revision = "cbe2acc6e667"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_price",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("product_id", sa.BIGINT(), nullable=True),
        sa.Column("establishment_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["establishment_id"],
            ["establishment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_price_establishment_id"),
        "product_price",
        ["establishment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_product_price_id"), "product_price", ["id"], unique=False)
    op.create_index(
        op.f("ix_product_price_product_id"), "product_price", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_price_product_id"), table_name="product_price")
    op.drop_index(op.f("ix_product_price_id"), table_name="product_price")
    op.drop_index(op.f("ix_product_price_establishment_id"), table_name="product_price")
    op.drop_table("product_price")
    # ### end Alembic commands ###
