"""Add cascade

Revision ID: 495db5ed8b81
Revises: 104837aaa066
Create Date: 2021-11-24 19:25:46.225144

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "495db5ed8b81"
down_revision = "104837aaa066"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("purchase_list_list_id_fkey", "purchase_list", type_="foreignkey")
    op.create_foreign_key(None, "purchase_list", "list", ["list_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "purchase_list", type_="foreignkey")
    op.create_foreign_key(
        "purchase_list_list_id_fkey", "purchase_list", "list", ["list_id"], ["id"]
    )

    # ### end Alembic commands ###
