"""Added list table

Revision ID: 511d26466776
Revises: 9a859ecddc24
Create Date: 2021-10-12 03:49:14.071916

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "511d26466776"
down_revision = "9a859ecddc24"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "list",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_list_id"), "list", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_establishment_location", "establishment", ["location"], unique=False)
    op.drop_index(op.f("ix_list_id"), table_name="list")
    op.drop_table("list")
    # ### end Alembic commands ###
