"""Added order table

Revision ID: a1ea0f7524ba
Revises: 1125a340929e
Create Date: 2021-11-12 07:46:39.408393

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a1ea0f7524ba"
down_revision = "1125a340929e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "establishment_purchase_list_order",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("purchase_list_id", sa.BIGINT(), nullable=True),
        sa.Column("establishment_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["establishment_id"],
            ["establishment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_list_id"],
            ["purchase_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_establishment_purchase_list_order_id"),
        "establishment_purchase_list_order",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_establishment_purchase_list_order_id"),
        table_name="establishment_purchase_list_order",
    )
    op.drop_table("establishment_purchase_list_order")
    # ### end Alembic commands ###
