"""Added fields

Revision ID: a4392f55d358
Revises: 495db5ed8b81
Create Date: 2021-11-29 19:05:41.554049

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a4392f55d358"
down_revision = "495db5ed8b81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notification", sa.Column("product_id", sa.BIGINT(), nullable=True))
    op.create_foreign_key(None, "notification", "product", ["product_id"], ["id"])
    op.add_column("purchase_list", sa.Column("latitude_southwest", sa.Float(), nullable=True))
    op.add_column("purchase_list", sa.Column("longitude_southwest", sa.Float(), nullable=True))
    op.add_column("purchase_list", sa.Column("latitude_northeast", sa.Float(), nullable=True))
    op.add_column("purchase_list", sa.Column("longitude_northeast", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("purchase_list", "longitude_northeast")
    op.drop_column("purchase_list", "latitude_northeast")
    op.drop_column("purchase_list", "longitude_southwest")
    op.drop_column("purchase_list", "latitude_southwest")
    op.drop_constraint(None, "notification", type_="foreignkey")
    op.drop_column("notification", "product_id")
    # ### end Alembic commands ###
