"""Added purchase and purchase list item

Revision ID: ac2e8624658c
Revises: 30dc864bba2d
Create Date: 2021-11-12 05:24:55.170622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ac2e8624658c"
down_revision = "30dc864bba2d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_list",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("color", sa.String(), nullable=True),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("spent", sa.Float(), nullable=True),
        sa.Column("list_id", sa.BIGINT(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["list.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_list_id"), "purchase_list", ["id"], unique=False)
    op.create_table(
        "purchase_list_item",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("is_buyed", sa.Boolean(), nullable=True),
        sa.Column("product_price_id", sa.BIGINT(), nullable=True),
        sa.Column("product_id", sa.BIGINT(), nullable=True),
        sa.Column("purchase_list_id", sa.BIGINT(), nullable=True),
        sa.Column("establishment_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["establishment_id"],
            ["establishment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_price_id"],
            ["product_price.id"],
        ),
        sa.ForeignKeyConstraint(
            ["purchase_list_id"],
            ["purchase_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_purchase_list_item_id"), "purchase_list_item", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_purchase_list_item_id"), table_name="purchase_list_item")
    op.drop_table("purchase_list_item")
    op.drop_index(op.f("ix_purchase_list_id"), table_name="purchase_list")
    op.drop_table("purchase_list")
    # ### end Alembic commands ###
