"""Added uuid field to list item

Revision ID: cbe2acc6e667
Revises: ce050627b9b6
Create Date: 2021-10-15 19:16:28.747162

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cbe2acc6e667"
down_revision = "ce050627b9b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("list_item", sa.Column("id_uuid", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f("ix_list_item_id_uuid"), "list_item", ["id_uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("list_item", "id_uuid")
