"""Added list item table

Revision ID: ce050627b9b6
Revises: 511d26466776
Create Date: 2021-10-15 18:00:01.316373

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce050627b9b6"
down_revision = "511d26466776"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "list_item",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.Column("product_id", sa.BIGINT(), nullable=True),
        sa.Column("list_id", sa.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["list_id"],
            ["list.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_list_item_id"), "list_item", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_list_item_id"), table_name="list_item")
    op.drop_table("list_item")
    # ### end Alembic commands ###
