"""Added table notification

Revision ID: e98e27a4aaf4
Revises: 4b5fef299b0b
Create Date: 2021-11-22 21:25:50.205496

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e98e27a4aaf4"
down_revision = "4b5fef299b0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=True),
        sa.Column("user_id", sa.BIGINT(), nullable=True),
        sa.Column("created_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notification_id"), "notification", ["id"], unique=False)
    op.drop_constraint("list_item_list_id_fkey", "list_item", type_="foreignkey")
    op.create_foreign_key(None, "list_item", "list", ["list_id"], ["id"], ondelete="cascade")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "list_item", type_="foreignkey")
    op.create_foreign_key("list_item_list_id_fkey", "list_item", "list", ["list_id"], ["id"])
    op.drop_index(op.f("ix_notification_id"), table_name="notification")
    op.drop_table("notification")
    # ### end Alembic commands ###
